In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
hello = tf.constant("Hello")
hello

<tf.Tensor: id=0, shape=(), dtype=string, numpy=b'Hello'>

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [6]:
print(hello)

tf.Tensor(b'Hello', shape=(), dtype=string)


# value print by normal method

In [7]:
tf.print(hello)

Hello


# value print by session

In [8]:
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
# Build a graph.
a = tf.constant("hello")
b = tf.constant("world")

# # Launch the graph in a session.
# sess = tf.compat.v1.Session()

# # Evaluate the tensor `c`.
# print(sess.run(a)) # prints 30.0
with tf.compat.v1.Session() as sess:
    result=sess.run(a)
print(result)
sess.close()

b'hello'


In [9]:
tf.compat.v1.disable_eager_execution()
mat_1 = tf.fill((5,5),10)
with tf.compat.v1.Session() as sess:
    result=sess.run(mat_1)
print(result)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [10]:
const=tf.constant(10)

In [11]:
print(mat_1)

Tensor("Fill:0", shape=(5, 5), dtype=int32)


In [12]:
zeros=tf.zeros((5,5))

In [13]:
ones=tf.ones((5,5))

In [14]:
randn=tf.random.normal((4,4),mean=0,stddev=1.0) # normal distribution

In [15]:
randu=tf.random.uniform((4,4),minval=0,maxval=1) # uniform distribution

In [16]:
myops=[const,mat_1,zeros,ones,randn,randu]

In [17]:
sess=tf.compat.v1.InteractiveSession()

In [18]:
for op in myops:
    # print(sess.run(op))
    print(op.eval())
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 0.1752228   0.20938283  2.2500699   1.1728197 ]
 [-0.80868495  1.7785778   0.5155206  -0.7285337 ]
 [-0.24227148  0.74496174 -0.61352    -0.470207  ]
 [-1.7724434  -0.37029147 -0.06809691  0.1899201 ]]


[[0.7834296  0.14781487 0.03581059 0.13495183]
 [0.25863063 0.44097626 0.5762185  0.16749334]
 [0.72158253 0.67846    0.93045974 0.21889663]
 [0.05229127 0.42652273 0.9505302  0.7004303 ]]




In [19]:
a=tf.constant([[1,2],[3,4]])
a.get_shape()

TensorShape([2, 2])

In [20]:
b=tf.constant([[10],[100]])
b.get_shape()

TensorShape([2, 1])

In [21]:
result=tf.matmul(a,b)

In [22]:
sess.run(result)

array([[210],
       [430]])