In [1]:
import tensorflow as tf
import numpy as np
tf.compat.v1.disable_eager_execution()

In [2]:
# help to crate sample
np.random.seed(101)
tf.compat.v1.set_random_seed(101)

In [3]:
rand_a=np.random.uniform(0,100,(5,5))
print(rand_a)

[[51.63986277 57.06675869  2.84742265 17.15216562 68.52769817]
 [83.38968626 30.69662197 89.36130797 72.15438618 18.99389542]
 [55.42275911 35.2131954  18.18924027 78.56017619 96.54832224]
 [23.23536618  8.35614337 60.35484223 72.89927573 27.62388285]
 [68.53063288 51.78674742  4.84845374 13.78692376 18.69674261]]


In [4]:
rand_b=np.random.uniform(0,100,(5,5))
print(rand_b)

[[99.43179012 52.06653967 57.87895355 73.48190583 54.19617722]
 [91.31535577 80.7920151  40.29978307 35.72243428 95.28767147]
 [34.36315779 86.50998163 83.02777122 53.81614492 92.24693726]
 [ 9.71464798 10.28474932 70.15072957 89.04798691 15.95603009]
 [27.55725449 67.24915297 16.4303124  70.13711366 48.76352222]]


In [5]:
a=tf.compat.v1.placeholder(tf.float32)
b=tf.compat.v1.placeholder(tf.float32) # placeholder mainly used for pass the data
# A placeholder is simply a variable that we will assign data to at a later date

In [6]:
add=a+b
mul=a*b

In [7]:
with tf.compat.v1.Session() as sess:
    add_result=sess.run(add,feed_dict={a:rand_a,b:rand_b})
    mul_result=sess.run(mul,feed_dict={a:rand_a,b:rand_b})
    
print(add_result,"\n\n",mul_result)

[[151.07166  109.1333    60.726376  90.63407  122.72388 ]
 [174.70505  111.48864  129.66109  107.87682  114.28157 ]
 [ 89.78592  121.723175 101.21701  132.37631  188.79526 ]
 [ 32.950016  18.640892 130.50557  161.94727   43.57991 ]
 [ 96.08789  119.035904  21.278767  83.92404   67.460266]] 

 [[5134.644    2971.2686    164.80583  1260.3738   3713.9392  ]
 [7614.759    2480.042    3601.2412   2577.5305   1809.884   ]
 [1904.5011   3046.2927   1510.212    4227.8057   8906.287   ]
 [ 225.72342    85.940834 4233.936    6491.534     440.7675  ]
 [1888.5161   3482.615      79.661606  966.97504   911.71906 ]]


In [8]:
v = tf.Variable([1, 2])
init = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    # Usage passing the session explicitly.
    print(v.eval(sess))
    print("\n")
    # Usage with the default session.  The 'with' block
    # above makes 'sess' the default session.
    print(v.eval())

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[1 2]


[1 2]
